// Code generated by MockGen. DO NOT EDIT.
// Source: repository/interfaces.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetUserById mocks base method.
func (m *MockRepositoryInterface) GetUserById(ctx context.Context, input GetUserByIdInput) (GetUserByIdOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", ctx, input)
	ret0, _ := ret[0].(GetUserByIdOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockRepositoryInterfaceMockRecorder) GetUserById(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUserById), ctx, input)
}

// GetUserByPhoneNumber mocks base method.
func (m *MockRepositoryInterface) GetUserByPhoneNumber(ctx context.Context, input GetUserByPhoneNumberInput) (GetUserByPhoneNumberOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByPhoneNumber", ctx, input)
	ret0, _ := ret[0].(GetUserByPhoneNumberOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByPhoneNumber indicates an expected call of GetUserByPhoneNumber.
func (mr *MockRepositoryInterfaceMockRecorder) GetUserByPhoneNumber(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByPhoneNumber", reflect.TypeOf((*MockRepositoryInterface)(nil).GetUserByPhoneNumber), ctx, input)
}

// InsertUsersData mocks base method.
func (m *MockRepositoryInterface) InsertUsersData(ctx context.Context, input InsertUsersDataInput) (InsertUsersDataOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUsersData", ctx, input)
	ret0, _ := ret[0].(InsertUsersDataOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertUsersData indicates an expected call of InsertUsersData.
func (mr *MockRepositoryInterfaceMockRecorder) InsertUsersData(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUsersData", reflect.TypeOf((*MockRepositoryInterface)(nil).InsertUsersData), ctx, input)
}

// UpdateCountById mocks base method.
func (m *MockRepositoryInterface) UpdateCountById(ctx context.Context, input UpdateCountByIdInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCountById", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCountById indicates an expected call of UpdateCountById.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateCountById(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCountById", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateCountById), ctx, input)
}

// UpdateFullNameByIdInput mocks base method.
func (m *MockRepositoryInterface) UpdateFullNameByIdInput(ctx context.Context, input UpdateFullNameByIdInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFullNameByIdInput", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFullNameByIdInput indicates an expected call of UpdateFullNameByIdInput.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateFullNameByIdInput(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFullNameByIdInput", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateFullNameByIdInput), ctx, input)
}
